spring:
  thymeleaf:
    mode: HTML5
    cache: false
    suffix: .html
    prefix: classpath:/static/views/
  application:
    name: RBAC管理
  resources:
    static-locations: ["classpath:/static"]
  mvc:
    static-path-pattern: /**
    view:
      prefix: /views/
      suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  #ES
#  elasticsearch:
#    rest:
#      uris: http://47.93.202.38:9200
  data:
    elasticsearch:
      cluster-name: dudj
      cluster-nodes: 47.93.202.38:9300
      repositories:
        enabled: true
      client:
        transport:
          sniff: false
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: static/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    port: 6379
    host: 47.93.202.38
